# Generated by Django 5.0 on 2023-12-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="private",
            field=models.BooleanField(db_default=models.Value(True)),
        ),
    ]
