# Generated by Django 4.2.4 on 2023-08-02 03:38

from decouple import config
from django.db import migrations


def setup(apps, schema_editor):
    from django.apps import apps
    competency = apps.get_model('project', 'EXCompetency')
    user = apps.get_model('core', 'User')

    competency.objects.bulk_create([
       competency(name="Create Vision and Strategy"),
       competency(name="Mobilize People"),
       competency(name="Uphold Integrity and Respect"),
       competency(name="Collaborate with Partners and Stakeholders"),
       competency(name="Promote Innovation and Guide Change"),
       competency(name="Achieve Results"),
    ])

    root = user.objects.create(username="root", )
    andrew = user.objects.create(username="andrew")
    root.is_superuser = True
    root.set_password(config("ROOT_PASSWORD"))
    root.save()
    andrew.set_password(config("ANDREW_PASSWORD"))
    andrew.save()

    Tag = apps.get_model('project', 'Tag')
    tags =[
        Tag(name="HR"),
        Tag(name="Urgent"),
        Tag(name="Important"),
    ]

    Tag.objects.bulk_create(tags)

    for tag in tags[1:]:
        tag.users.add(andrew)

def teardown(apps, schema_editor):
    from django.apps import apps
    User = apps.get_model('core', 'User')
    User.objects.filter(username__in=["root","andrew"]).delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(setup, teardown),
    ]

