# Generated by Django 5.0.6 on 2024-05-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_remove_contact_my_projects_project_viewers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
