# Generated by Django 4.2.7 on 2023-11-05 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_add_basic_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="users",
        ),
    ]
