# Generated by Django 5.0.6 on 2024-05-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_project_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
