# Generated by Django 5.0.1 on 2024-01-05 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamwork",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_items",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="streamwork",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_items",
                to="project.stream",
            ),
        ),
    ]
