# Generated by Django 4.2.7 on 2023-11-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_remove_team_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
