# Generated by Django 5.0.6 on 2024-05-20 02:10

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_group_system"),
        ("project", "0004_alter_task_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectGroup",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name="team",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_team",
                to="core.group",
            ),
        ),
    ]
