# Generated by Django 5.0.1 on 2024-01-08 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_alter_streamwork_project_alter_streamwork_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamwork",
            name="start_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="streamwork",
            name="done",
            field=models.BooleanField(blank=True, db_default=models.Value(False)),
        ),
        migrations.AlterField(
            model_name="streamwork",
            name="target_date",
            field=models.DateField(blank=True),
        ),
    ]
