# Generated by Django 5.0b1 on 2023-11-18 20:10

from  core import rest
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_team_private_alter_team_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="themework",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="themework",
            name="competency",
        ),
        migrations.RemoveField(
            model_name="themework",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="themework",
            name="teams",
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                rest.belongs_to,
                rest.AutoCompleteREST,
            ),
        ),
        migrations.CreateModel(
            name="StreamWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_date", models.DateTimeField()),
                ("name", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("addstamp", models.DateTimeField(auto_now_add=True)),
                ("editstamp", models.DateTimeField(auto_now=True)),
                (
                    "competency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project.excompetency",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.contact",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_details",
                        to="project.stream",
                    ),
                ),
                ("teams", models.ManyToManyField(blank=True, to="project.team")),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                rest.belongs_to,
                rest.AutoCompleteNexus,
            ),
        ),
        migrations.DeleteModel(
            name="Theme",
        ),
        migrations.DeleteModel(
            name="ThemeWork",
        ),
    ]
