# Generated by Django 5.0.1 on 2024-01-09 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_streamwork_start_date_alter_streamwork_done_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StreamWork",
            new_name="Task",
        ),
    ]
