# Generated by Django 5.0b1 on 2023-11-18 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_remove_themework_theme_remove_themework_competency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamwork",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_items",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="streamwork",
            name="stream",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_items",
                to="project.stream",
            ),
        ),
    ]
