# Generated by Django 5.0.6 on 2024-05-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_projectuser_alter_contact_account_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="group",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="group",
        ),
        migrations.RemoveField(
            model_name="timereport",
            name="group",
        ),
        migrations.AlterField(
            model_name="project",
            name="teams",
            field=models.ManyToManyField(to="project.projectgroup"),
        ),
        migrations.AlterField(
            model_name="task",
            name="teams",
            field=models.ManyToManyField(blank=True, to="project.projectgroup"),
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
