# Generated by Django 5.0 on 2023-12-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_streamwork_project_alter_streamwork_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamwork",
            name="done",
            field=models.BooleanField(db_default=models.Value(False)),
        ),
    ]
