# Generated by Django 5.0 on 2023-12-07 00:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0007_streamwork_done"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stream",
            unique_together={("name", "project")},
        ),
    ]
