# Generated by Django 5.0.1 on 2024-01-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0007_stream_project_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
