# Generated by Django 5.0.6 on 2024-05-20 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_remove_contact_group_remove_tag_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="group",
            field=models.ForeignKey(
                blank=True,
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts",
                to="project.projectgroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="group",
            field=models.ForeignKey(
                blank=True,
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tags",
                to="project.projectgroup",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="group",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="project.projectgroup",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="teams",
            field=models.ManyToManyField(
                related_name="projects_supporting", to="project.projectgroup"
            ),
        ),
    ]
