# Generated by Django 5.0.2 on 2024-02-18 04:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_alter_task_target_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="done",
            field=models.BooleanField(blank=True, db_default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.contact",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="project.stream",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="private",
            field=models.BooleanField(db_default=True),
        ),
    ]
