# Generated by Django 5.0.6 on 2024-05-21 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_contact_group_tag_group_alter_project_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="private",
            field=models.BooleanField(db_default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="private_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="private_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
