# Generated by Django 5.0.6 on 2024-05-23 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_project_private_project_private_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="name",
            new_name="name_en",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="text",
            new_name="text_en",
        ),
        migrations.AddField(
            model_name="project",
            name="addstamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="long_term_outcomes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="name_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="short_term_outcomes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="text_fr",
            field=models.TextField(blank=True, null=True),
        ),
    ]
