# Generated by Django 5.0.4 on 2024-04-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_alter_task_done_alter_task_lead_alter_task_project_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["done", "start_date"]},
        ),
        migrations.AlterField(
            model_name="project",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
