# Generated by Django 5.0.6 on 2024-05-23 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_rename_name_project_name_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="lead",
        ),
        migrations.AddField(
            model_name="project",
            name="leads",
            field=models.ManyToManyField(blank=True, to="project.contact"),
        ),
        migrations.AlterField(
            model_name="project",
            name="private_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="private_projects",
                to="project.projectuser",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="viewers",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="project.projectuser"
            ),
        ),
    ]
