# Generated by Django 5.0.4 on 2024-04-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_alter_task_options_alter_project_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
