# Generated by Django 5.0.6 on 2024-05-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_projectstatus_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="addstamp",
            field=models.DateTimeField(null=True),
        ),
    ]
