# Generated by Django 5.0.6 on 2024-05-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0013_alter_project_addstamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="excompetency",
            old_name="name",
            new_name="name_en",
        ),
    ]
