# Generated by Django 5.0.6 on 2024-05-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0014_rename_name_excompetency_name_en"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stream",
            old_name="name",
            new_name="name_en",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="name",
            new_name="name_en",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="text",
            new_name="text_en",
        ),
        migrations.AlterUniqueTogether(
            name="stream",
            unique_together={("name_en", "project")},
        ),
        migrations.AddField(
            model_name="stream",
            name="name_fr",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="name_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="text_fr",
            field=models.TextField(blank=True, null=True),
        ),
    ]
