# Generated by Django 5.0.6 on 2024-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0015_rename_name_stream_name_en_rename_name_task_name_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectstatus",
            options={"verbose_name": "Status", "verbose_name_plural": "Statuses"},
        ),
        migrations.AddField(
            model_name="settings",
            name="projects_filter",
            field=models.JSONField(db_default="{}"),
        ),
    ]
