# Generated by Django 5.0.6 on 2024-05-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0016_alter_projectstatus_options_settings_projects_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="excompetency",
            name="name_fr",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="projectstatus",
            name="name_fr",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
