# Generated by Django 5.0.6 on 2024-05-28 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0017_excompetency_name_fr_projectstatus_name_fr"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectlogentry",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_entries",
                to="project.projectuser",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="settings",
            name="user",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.projectuser",
            ),
        ),
        migrations.AlterField(
            model_name="timereport",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.projectuser",
            ),
        ),
    ]
