# Generated by Django 5.0.6 on 2024-05-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0018_alter_contact_group_alter_tag_group_alter_team_group_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="internal",
        ),
        migrations.RemoveField(
            model_name="team",
            name="private",
        ),
        migrations.AddField(
            model_name="team",
            name="public",
            field=models.BooleanField(db_default=False),
        ),
    ]
