# Generated by Django 5.0.6 on 2024-05-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0019_remove_team_internal_remove_team_private_team_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="public",
            field=models.BooleanField(db_default=False),
        ),
    ]
