# Generated by Django 5.0.6 on 2024-06-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0021_alter_project_teams_alter_settings_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timereport",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
