# Generated by Django 5.0.6 on 2024-05-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0022_remove_projectlogentry_project_projectlog_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectlog",
            name="group",
        ),
        migrations.RemoveField(
            model_name="projectlogentry",
            name="group",
        ),
    ]
