# Generated by Django 5.0.6 on 2024-06-23 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0023_alter_timereport_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="work_hours",
            field=models.DecimalField(
                db_default=37.5,
                decimal_places=1,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
