# Generated by Django 5.0.6 on 2024-06-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0024_settings_work_hours"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="teams",
            new_name="partners",
        ),
    ]
