# Generated by Django 5.0.6 on 2024-06-30 02:46

import django.db.models.deletion
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_user_belongs_to"),
        ("project", "0026_project_project_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyProjectGroup",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.group",),
            managers=[
                ("objects", project.models.ProjectGroupManager()),
            ],
        ),
        migrations.RenameField(
            model_name="project",
            old_name="leads",
            new_name="project_team",
        ),
        migrations.AddField(
            model_name="project",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_i_lead",
                to="project.projectuser",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="partners",
            field=models.ManyToManyField(blank=True, to="project.projectgroup"),
        ),
    ]
