# Generated by Django 5.0.7 on 2024-08-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0028_delete_minproject_alter_projectuser_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmallProject",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("project.project",),
        ),
        migrations.AddField(
            model_name="projectstatus",
            name="order",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
