# Generated by Django 5.0.7 on 2024-08-02 03:20

import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0029_smallproject_projectstatus_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("name_en", models.CharField(max_length=300, unique=True)),
                ("name_fr", models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name="projectstatus",
            options={
                "ordering": ["order"],
                "verbose_name": "Status",
                "verbose_name_plural": "Statuses",
            },
        ),
    ]
