# Generated by Django 5.0.7 on 2024-08-02 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0030_projecttype_alter_projectstatus_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="project.projecttype",
            ),
            preserve_default=False,
        ),
    ]
