# Generated by Django 5.0.7 on 2024-08-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0031_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectstatus",
            name="active",
            field=models.BooleanField(db_default=True),
        ),
    ]
