# Generated by Django 5.0.8 on 2024-08-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0034_task_old_target_dates"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="old_target_dates",
            new_name="target_date_history",
        ),
        migrations.AddField(
            model_name="task",
            name="done_history",
            field=models.JSONField(default=list),
        ),
    ]
