# Generated by Django 5.1 on 2024-08-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0038_rename_projectlogentry_projectlog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectDoc",
            new_name="DocLink",
        ),
        migrations.RenameModel(
            old_name="ProjectLog",
            new_name="Log",
        ),
    ]
