# Generated by Django 5.1 on 2024-08-13 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0039_rename_projectdoc_doclink_rename_projectlog_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="project.project",
            ),
        ),
    ]
