# Generated by Django 5.1 on 2024-08-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0041_link_delete_doclink"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="title",
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="link",
            field=models.URLField(max_length=600),
        ),
    ]
