# Generated by Django 5.1 on 2024-08-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0042_link_title_alter_link_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="done_history",
        ),
        migrations.AddField(
            model_name="task",
            name="done_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="link",
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name="link",
            name="title",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
