# Generated by Django 4.2.4 on 2023-08-02 03:38

from decouple import config
from django.db import migrations


def create_product(apps, schema_editor):
    from django.apps import apps
    competency = apps.get_model('core', 'EXCompetency')
    user = apps.get_model('core', 'User')

    competency.objects.bulk_create([
       competency(name="Create Vision and Strategy"),
       competency(name="Mobilize People"),
       competency(name="Uphold Integrity and Respect"),
       competency(name="Collaborate with Partners and Stakeholders"),
       competency(name="Promote Innovation and Guide Change"),
       competency(name="Achieve Results"),
    ])

    root = user.objects.create(username="root", )
    andrew = user.objects.create(username="andrew")
    root.is_superuser = True
    root.set_password(config("ROOT_PASSWORD"))
    root.save()
    andrew.set_password(config("ANDREW_PASSWORD"))
    andrew.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_product, migrations.RunPython.noop),
    ]

