# Generated by Django 5.0.6 on 2024-05-18 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_group_alter_user_groups_alter_user_main_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="group",
        ),
    ]
