# Generated by Django 5.0.6 on 2024-05-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_group_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="system",
            field=models.BooleanField(db_default=False),
        ),
    ]
