# Generated by Django 5.0.6 on 2024-05-22 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_main_group_user_belongs_to_user_manages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="name",
            new_name="name_en",
        ),
        migrations.AddField(
            model_name="group",
            name="acronym_en",
            field=models.CharField(
                blank=True, max_length=10, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="acronym_fr",
            field=models.CharField(
                blank=True, max_length=10, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="name_fr",
            field=models.CharField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.group",
            ),
        ),
    ]
