# Generated by Django 5.0.6 on 2024-06-02 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_name_group_name_en_group_acronym_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="acronym_en",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="acronym_fr",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="name_en",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="name_fr",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="manages",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.group",
                unique=True,
            ),
        ),
    ]
