# Generated by Django 5.0.6 on 2024-06-02 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_group_acronym_en_alter_group_acronym_fr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="manages",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.group",
            ),
        ),
    ]
